applications:
  HTTP:
    protocol: tcp
    port: 80

  HTTPS:
    protocol: tcp
    port: 443

  SSH:
    protocol: tcp
    port: 22

  DNS:
    protocol: tcp
    port: 53

  FTP:
    protocol: tcp
    port: 21

  SNMP:
    protocol: udp
    port: 161
  SMTP:
    protocol: tcp
    port: 25

 RDP:
    protocol: tcp
    port: 3389

 TELNET:
    protocol: tcp
    port: 23

 NTP:
    protocol: udp
    port: 123

  IMAP:
    protocol: tcp
    port: 143

  POP3:
    protocol: tcp
    port: 110

  LDAP:
    protocol: tcp
    port: 389